
package knowyourtown.localdb.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "People", targetNamespace = "http://webservice.localdb.knowyourtown/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface People {


    /**
     * 
     * @param personId
     * @return
     *     returns knowyourtown.localdb.webservice.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.ReadPersonResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/readPersonRequest", output = "http://webservice.localdb.knowyourtown/People/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @return
     *     returns java.util.List<knowyourtown.localdb.webservice.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "getPeopleList", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetPeopleList")
    @ResponseWrapper(localName = "getPeopleListResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetPeopleListResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/getPeopleListRequest", output = "http://webservice.localdb.knowyourtown/People/getPeopleListResponse")
    public List<Person> getPeopleList();

    /**
     * 
     * @param person
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.CreatePersonResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/createPersonRequest", output = "http://webservice.localdb.knowyourtown/People/createPersonResponse")
    public int createPerson(
        @WebParam(name = "person", targetNamespace = "http://webservice.localdb.knowyourtown/")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.UpdatePersonResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/updatePersonRequest", output = "http://webservice.localdb.knowyourtown/People/updatePersonResponse")
    public int updatePerson(
        @WebParam(name = "person", targetNamespace = "http://webservice.localdb.knowyourtown/")
        Person person);

    /**
     * 
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.DeletePersonResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/deletePersonRequest", output = "http://webservice.localdb.knowyourtown/People/deletePersonResponse")
    public int deletePerson(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param placeId
     * @param personId
     * @param placeTypeId
     * @return
     *     returns knowyourtown.localdb.webservice.Place
     */
    @WebMethod
    @WebResult(name = "place", targetNamespace = "")
    @RequestWrapper(localName = "readPlace", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.ReadPlace")
    @ResponseWrapper(localName = "readPlaceResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.ReadPlaceResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/readPlaceRequest", output = "http://webservice.localdb.knowyourtown/People/readPlaceResponse")
    public Place readPlace(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "placeTypeId", targetNamespace = "")
        String placeTypeId,
        @WebParam(name = "placeId", targetNamespace = "")
        int placeId);

    /**
     * 
     * @param personId
     * @return
     *     returns java.util.List<knowyourtown.localdb.webservice.Place>
     */
    @WebMethod
    @WebResult(name = "placeList", targetNamespace = "")
    @RequestWrapper(localName = "readLastPlace", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.ReadLastPlace")
    @ResponseWrapper(localName = "readLastPlaceResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.ReadLastPlaceResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/readLastPlaceRequest", output = "http://webservice.localdb.knowyourtown/People/readLastPlaceResponse")
    public List<Place> readLastPlace(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param personId
     * @param placeTypeId
     * @return
     *     returns knowyourtown.localdb.webservice.Place
     */
    @WebMethod
    @WebResult(name = "place", targetNamespace = "")
    @RequestWrapper(localName = "readLastPlaceByType", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.ReadLastPlaceByType")
    @ResponseWrapper(localName = "readLastPlaceByTypeResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.ReadLastPlaceByTypeResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/readLastPlaceByTypeRequest", output = "http://webservice.localdb.knowyourtown/People/readLastPlaceByTypeResponse")
    public Place readLastPlaceByType(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "placeTypeId", targetNamespace = "")
        String placeTypeId);

    /**
     * 
     * @param personId
     * @param placeTypeId
     * @return
     *     returns java.util.List<knowyourtown.localdb.webservice.Place>
     */
    @WebMethod
    @WebResult(name = "placeList", targetNamespace = "")
    @RequestWrapper(localName = "getPlaceHistory", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetPlaceHistory")
    @ResponseWrapper(localName = "getPlaceHistoryResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetPlaceHistoryResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/getPlaceHistoryRequest", output = "http://webservice.localdb.knowyourtown/People/getPlaceHistoryResponse")
    public List<Place> getPlaceHistory(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "placeTypeId", targetNamespace = "")
        String placeTypeId);

    /**
     * 
     * @param nPlace
     * @param personId
     * @param placeTypeId
     * @return
     *     returns java.util.List<knowyourtown.localdb.webservice.Place>
     */
    @WebMethod
    @WebResult(name = "placeList", targetNamespace = "")
    @RequestWrapper(localName = "getSomePlace", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetSomePlace")
    @ResponseWrapper(localName = "getSomePlaceResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetSomePlaceResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/getSomePlaceRequest", output = "http://webservice.localdb.knowyourtown/People/getSomePlaceResponse")
    public List<Place> getSomePlace(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "placeTypeId", targetNamespace = "")
        String placeTypeId,
        @WebParam(name = "nPlace", targetNamespace = "")
        int nPlace);

    /**
     * 
     * @param personId
     * @param place
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "placeId", targetNamespace = "")
    @RequestWrapper(localName = "createPlace", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.CreatePlace")
    @ResponseWrapper(localName = "createPlaceResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.CreatePlaceResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/createPlaceRequest", output = "http://webservice.localdb.knowyourtown/People/createPlaceResponse")
    public int createPlace(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "place", targetNamespace = "http://webservice.localdb.knowyourtown/")
        Place place);

    /**
     * 
     * @param personId
     * @param place
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "placeId", targetNamespace = "")
    @RequestWrapper(localName = "updatePlace", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.UpdatePlace")
    @ResponseWrapper(localName = "updatePlaceResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.UpdatePlaceResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/updatePlaceRequest", output = "http://webservice.localdb.knowyourtown/People/updatePlaceResponse")
    public int updatePlace(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "place", targetNamespace = "http://webservice.localdb.knowyourtown/")
        Place place);

    /**
     * 
     * @param placeId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deletePlace", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.DeletePlace")
    @ResponseWrapper(localName = "deletePlaceResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.DeletePlaceResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/deletePlaceRequest", output = "http://webservice.localdb.knowyourtown/People/deletePlaceResponse")
    public int deletePlace(
        @WebParam(name = "placeId", targetNamespace = "")
        int placeId);

    /**
     * 
     * @param placeTypeId
     * @return
     *     returns knowyourtown.localdb.webservice.PlaceType
     */
    @WebMethod
    @WebResult(name = "placeType", targetNamespace = "")
    @RequestWrapper(localName = "readPlaceType", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.ReadPlaceType")
    @ResponseWrapper(localName = "readPlaceTypeResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.ReadPlaceTypeResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/readPlaceTypeRequest", output = "http://webservice.localdb.knowyourtown/People/readPlaceTypeResponse")
    public PlaceType readPlaceType(
        @WebParam(name = "placeTypeId", targetNamespace = "")
        int placeTypeId);

    /**
     * 
     * @param type
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "idPlaceType", targetNamespace = "")
    @RequestWrapper(localName = "getIdPlaceTypeByType", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetIdPlaceTypeByType")
    @ResponseWrapper(localName = "getIdPlaceTypeByTypeResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetIdPlaceTypeByTypeResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/getIdPlaceTypeByTypeRequest", output = "http://webservice.localdb.knowyourtown/People/getIdPlaceTypeByTypeResponse")
    public int getIdPlaceTypeByType(
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @return
     *     returns java.util.List<knowyourtown.localdb.webservice.PlaceType>
     */
    @WebMethod
    @WebResult(name = "placeTypeList", targetNamespace = "")
    @RequestWrapper(localName = "getPlaceTypeList", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetPlaceTypeList")
    @ResponseWrapper(localName = "getPlaceTypeListResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetPlaceTypeListResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/getPlaceTypeListRequest", output = "http://webservice.localdb.knowyourtown/People/getPlaceTypeListResponse")
    public List<PlaceType> getPlaceTypeList();

    /**
     * 
     * @param personId
     * @return
     *     returns java.util.List<knowyourtown.localdb.webservice.Suggestion>
     */
    @WebMethod
    @WebResult(name = "suggestionList", targetNamespace = "")
    @RequestWrapper(localName = "getSuggestions", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetSuggestions")
    @ResponseWrapper(localName = "getSuggestionsResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetSuggestionsResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/getSuggestionsRequest", output = "http://webservice.localdb.knowyourtown/People/getSuggestionsResponse")
    public List<Suggestion> getSuggestions(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param suggestionId
     * @param personId
     * @param placeTypeId
     * @return
     *     returns knowyourtown.localdb.webservice.Suggestion
     */
    @WebMethod
    @WebResult(name = "suggestion", targetNamespace = "")
    @RequestWrapper(localName = "readSuggestion", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.ReadSuggestion")
    @ResponseWrapper(localName = "readSuggestionResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.ReadSuggestionResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/readSuggestionRequest", output = "http://webservice.localdb.knowyourtown/People/readSuggestionResponse")
    public Suggestion readSuggestion(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "placeTypeId", targetNamespace = "")
        String placeTypeId,
        @WebParam(name = "suggestionId", targetNamespace = "")
        int suggestionId);

    /**
     * 
     * @param personId
     * @param placeTypeId
     * @return
     *     returns java.util.List<knowyourtown.localdb.webservice.Suggestion>
     */
    @WebMethod
    @WebResult(name = "suggestionList", targetNamespace = "")
    @RequestWrapper(localName = "getSuggestionHistory", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetSuggestionHistory")
    @ResponseWrapper(localName = "getSuggestionHistoryResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetSuggestionHistoryResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/getSuggestionHistoryRequest", output = "http://webservice.localdb.knowyourtown/People/getSuggestionHistoryResponse")
    public List<Suggestion> getSuggestionHistory(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "placeTypeId", targetNamespace = "")
        String placeTypeId);

    /**
     * 
     * @param suggestion
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "suggestionId", targetNamespace = "")
    @RequestWrapper(localName = "createSuggestion", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.CreateSuggestion")
    @ResponseWrapper(localName = "createSuggestionResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.CreateSuggestionResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/createSuggestionRequest", output = "http://webservice.localdb.knowyourtown/People/createSuggestionResponse")
    public int createSuggestion(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "suggestion", targetNamespace = "http://webservice.localdb.knowyourtown/")
        Suggestion suggestion);

    /**
     * 
     * @param suggestion
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "suggestionId", targetNamespace = "")
    @RequestWrapper(localName = "updateSuggestion", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.UpdateSuggestion")
    @ResponseWrapper(localName = "updateSuggestionResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.UpdateSuggestionResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/updateSuggestionRequest", output = "http://webservice.localdb.knowyourtown/People/updateSuggestionResponse")
    public int updateSuggestion(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "suggestion", targetNamespace = "http://webservice.localdb.knowyourtown/")
        Suggestion suggestion);

    /**
     * 
     * @param suggestionId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteSuggestion", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.DeleteSuggestion")
    @ResponseWrapper(localName = "deleteSuggestionResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.DeleteSuggestionResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/deleteSuggestionRequest", output = "http://webservice.localdb.knowyourtown/People/deleteSuggestionResponse")
    public int deleteSuggestion(
        @WebParam(name = "suggestionId", targetNamespace = "")
        int suggestionId);

    /**
     * 
     * @param personId
     * @param title
     * @return
     *     returns knowyourtown.localdb.webservice.Suggestion
     */
    @WebMethod
    @WebResult(name = "suggestion", targetNamespace = "")
    @RequestWrapper(localName = "getSuggestionByTitle", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetSuggestionByTitle")
    @ResponseWrapper(localName = "getSuggestionByTitleResponse", targetNamespace = "http://webservice.localdb.knowyourtown/", className = "knowyourtown.localdb.webservice.GetSuggestionByTitleResponse")
    @Action(input = "http://webservice.localdb.knowyourtown/People/getSuggestionByTitleRequest", output = "http://webservice.localdb.knowyourtown/People/getSuggestionByTitleResponse")
    public Suggestion getSuggestionByTitle(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "title", targetNamespace = "")
        String title);

}
